source("renv/activate.R")
options(renv.config.pak.enabled = TRUE)
options(renv.config.ppm.enabled = FALSE)
options(repos = c(CRAN = "https://p3m.dev/cran/__linux__/noble/latest"))
.libPaths("/usr/local/lib/R/site-library")
